config/routes.rb
Rails.application.routes.draw do
  get '/products/new', to: 'products#new', as: :new_product
  get '/products', to: 'products#index', as: :products
  get '/products/:id', to: 'products#show', as: :product
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end

    def show
       @product = Product.find(params[:id])
    end
    
    def new
        @product = Product.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vendelo con ruby on Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h2>Productos :</h2>


<%= Date.today %>
<br />
<% @products.each do |product| %>
 <%= link_to  product_path(product.id) do %> 
<h2><%= product.title   %></h2>
<span>Precio: $<%= product.price   %></span>
<% end   %>
<% end   %>

app/views/products/new.html.erb
<h2>AÑADIR PRODUCTOS</h2>


<%=  form_with model: @product do |form|   %>
<div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
<div>
    <%= form.label :description %>
    <%= form.text_area :description %>
    </div>
<div>
    <%= form.label :price %>
    <%= form.number_field :price %>
    </div>

    <div><%= form.submit%></div>
<% end %>

app/views/products/show.html.erb
<h2>producto</h2>
<h3><%= @product.description%></h3>

app/views/shared/_header.html.erb
<header>
<%= link_to products_path do%>
    <h1>Vende tu producto</h1>
    <%end%>
    <nav>
        <span>  <%= link_to "Añadir producto:", new_product_path %></span>
        <span>2</span>
        <span>3</span>
        <span>4</span>
    </nav>
</header>